
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

output "api-gateway_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.api_gateway.service_uri
}
output "planner-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.planner_agent.service_uri
}
output "solver-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.solver_agent.service_uri
}
output "critic-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.critic_agent.service_uri
}
output "tool-fabric_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.tool_fabric.service_uri
}
output "risk-layer_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.risk_layer.service_uri
}
output "global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.global_lb_frontend.external_ip
}
output "global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.global_lb_frontend.external_ipv6_address
}
output "global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.global_lb_frontend.ip_address_internal_managed_http
}
output "global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.global_lb_frontend.ip_address_internal_managed_https
}
output "redis-cache_host" {
  description = "The IP address of the instance."
  value       = module.redis_cache.host
}
output "redis-cache_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.redis_cache.port
}
output "api-gateway-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.api_gateway_us_east1.service_uri
}
output "planner-agent-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.planner_agent_us_east1.service_uri
}
output "solver-agent-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.solver_agent_us_east1.service_uri
}
output "critic-agent-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.critic_agent_us_east1.service_uri
}
output "tool-fabric-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.tool_fabric_us_east1.service_uri
}
output "risk-layer-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.risk_layer_us_east1.service_uri
}
output "redis-cache-us-east1_host" {
  description = "The IP address of the instance."
  value       = module.redis_cache_us_east1.host
}
output "redis-cache-us-east1_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.redis_cache_us_east1.port
}
output "policy-engine-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.policy_engine_cloud_run.service_uri
}
output "policy-engine-cloud-run-us-east1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.policy_engine_cloud_run_us_east1.service_uri
}
